// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Roaster_Generator.Data;

#nullable disable

namespace Roaster_Generator.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260907172315_AddEmployeeTargetHoursAndRosters")]
    partial class AddEmployeeTargetHoursAndRosters
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Roaster_Generator.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId")
                        .IsUnique()
                        .HasFilter("employee_id IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Roaster_Generator.Entities.DemandColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("DemandPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("demand_plan_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.Property<int>("Position")
                        .HasColumnType("integer")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.HasIndex("DemandPlanId", "Position")
                        .IsUnique();

                    b.ToTable("demand_columns", (string)null);
                });

            modelBuilder.Entity("Roaster_Generator.Entities.DemandPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.HasKey("Id");

                    b.HasIndex("WeekStart")
                        .IsUnique();

                    b.ToTable("demand_plans", (string)null);
                });

            modelBuilder.Entity("Roaster_Generator.Entities.DemandRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<Guid>("DemandPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("demand_plan_id");

                    b.Property<int>("Hour")
                        .HasColumnType("integer")
                        .HasColumnName("hour");

                    b.HasKey("Id");

                    b.HasIndex("DemandPlanId", "Hour")
                        .IsUnique();

                    b.ToTable("demand_rows", (string)null);
                });

            modelBuilder.Entity("Roaster_Generator.Entities.DemandValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<decimal?>("Deliveries")
                        .HasColumnType("numeric(10,2)")
                        .HasColumnName("deliveries");

                    b.Property<int?>("Demand")
                        .HasColumnType("integer")
                        .HasColumnName("demand");

                    b.Property<Guid>("DemandColumnId")
                        .HasColumnType("uuid")
                        .HasColumnName("demand_column_id");

                    b.Property<Guid>("DemandRowId")
                        .HasColumnType("uuid")
                        .HasColumnName("demand_row_id");

                    b.HasKey("Id");

                    b.HasIndex("DemandColumnId");

                    b.HasIndex("DemandRowId", "DemandColumnId")
                        .IsUnique();

                    b.ToTable("demand_values", (string)null);
                });

            modelBuilder.Entity("Roaster_Generator.Entities.Employee", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("employee_number");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("phone_number");

                    b.Property<int>("TargetHours")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(20)
                        .HasColumnName("target_hours");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeNumber")
                        .IsUnique();

                    b.ToTable("employees", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("3a27962b-3138-4e8c-9c5c-2fa7c817073f"),
                            EmployeeNumber = "9100",
                            FirstName = "Marcin",
                            IsActive = true,
                            LastName = "Galkowski",
                            PhoneNumber = "0858340019",
                            TargetHours = 20
                        },
                        new
                        {
                            Id = new Guid("00495efa-eb46-43f6-bbe9-fa56b28bb9a2"),
                            EmployeeNumber = "7870",
                            FirstName = "Arshad B",
                            IsActive = true,
                            LastName = "omarkhel",
                            PhoneNumber = "0899427870",
                            TargetHours = 20
                        },
                        new
                        {
                            Id = new Guid("5ad2fc14-cda5-482e-a48a-14bbd43333ed"),
                            EmployeeNumber = "6116",
                            FirstName = "Tony",
                            IsActive = true,
                            LastName = "Lukose",
                            PhoneNumber = "0894466116",
                            TargetHours = 20
                        },
                        new
                        {
                            Id = new Guid("fe3538ee-640b-44dc-895e-e859eec2d2c7"),
                            EmployeeNumber = "7229",
                            FirstName = "Pavishkumar B",
                            IsActive = true,
                            LastName = "Kumararamalingam",
                            PhoneNumber = "0892597229",
                            TargetHours = 20
                        },
                        new
                        {
                            Id = new Guid("3b64e926-651a-422b-bc62-da27dd846356"),
                            EmployeeNumber = "2075",
                            FirstName = "Shahram B",
                            IsActive = true,
                            LastName = "Sajawal",
                            PhoneNumber = "0858402075",
                            TargetHours = 20
                        },
                        new
                        {
                            Id = new Guid("e2aeb96b-6937-42ac-8e67-37fe06876a9e"),
                            EmployeeNumber = "5385",
                            FirstName = "Mustafa B",
                            IsActive = true,
                            LastName = "Kanchwala",
                            PhoneNumber = "0894915385",
                            TargetHours = 20
                        },
                        new
                        {
                            Id = new Guid("4777bddb-029a-4248-8393-6bea8a61f7ae"),
                            EmployeeNumber = "2004",
                            FirstName = "Subhan",
                            IsActive = true,
                            LastName = "Aqeel",
                            PhoneNumber = "0831243953",
                            TargetHours = 20
                        },
                        new
                        {
                            Id = new Guid("6077cbdb-db89-4643-96ab-a1c2e32cfee1"),
                            EmployeeNumber = "2138",
                            FirstName = "Nanthu",
                            IsActive = true,
                            LastName = "Njaneswaran",
                            PhoneNumber = "0872462138",
                            TargetHours = 20
                        },
                        new
                        {
                            Id = new Guid("4da853a0-b154-4fce-84d3-63512d0ba73f"),
                            EmployeeNumber = "3889",
                            FirstName = "Pradeep",
                            IsActive = true,
                            LastName = "Sreekumari",
                            PhoneNumber = "0894133889",
                            TargetHours = 20
                        },
                        new
                        {
                            Id = new Guid("d81a3e8a-0a9c-47fd-b568-5cbc2eef9f17"),
                            EmployeeNumber = "1840",
                            FirstName = "ANDREWS",
                            IsActive = true,
                            LastName = "ABRAHAM CHACKO",
                            PhoneNumber = "0831431840",
                            TargetHours = 20
                        },
                        new
                        {
                            Id = new Guid("9e3526b7-d00c-4bd3-b05f-7d15ece9d21b"),
                            EmployeeNumber = "3512",
                            FirstName = "Bibin",
                            IsActive = true,
                            LastName = "Baby",
                            PhoneNumber = "0892403512",
                            TargetHours = 20
                        },
                        new
                        {
                            Id = new Guid("f7143b02-3df5-4f28-95a5-6946ddfade4f"),
                            EmployeeNumber = "7179",
                            FirstName = "SunilValliparampil",
                            IsActive = true,
                            LastName = "Alex",
                            PhoneNumber = "0892097179",
                            TargetHours = 20
                        },
                        new
                        {
                            Id = new Guid("b40abf4f-0a67-4a68-b39d-98ce2431efae"),
                            EmployeeNumber = "3040",
                            FirstName = "Jomon",
                            IsActive = true,
                            LastName = "Thottiparambil Johny",
                            PhoneNumber = "0874520403",
                            TargetHours = 20
                        },
                        new
                        {
                            Id = new Guid("796f9cd8-7132-45e4-b4ce-afdce4476e22"),
                            EmployeeNumber = "5512",
                            FirstName = "Rajendran",
                            IsActive = true,
                            LastName = "Pandiarajan",
                            PhoneNumber = "0892315512",
                            TargetHours = 20
                        },
                        new
                        {
                            Id = new Guid("cfddadab-f4b8-4fbd-945c-4faef19ef2e4"),
                            EmployeeNumber = "7090",
                            FirstName = "WEI",
                            IsActive = true,
                            LastName = "WANG",
                            PhoneNumber = "0870570907",
                            TargetHours = 20
                        },
                        new
                        {
                            Id = new Guid("f07d963f-272a-4636-a7e5-ee6af713bfa5"),
                            EmployeeNumber = "8944",
                            FirstName = "Alban",
                            IsActive = true,
                            LastName = "Keane",
                            PhoneNumber = "0858388944",
                            TargetHours = 20
                        },
                        new
                        {
                            Id = new Guid("877293ba-4650-488a-a0a7-1eff8f5d02f5"),
                            EmployeeNumber = "9627",
                            FirstName = "Joveski",
                            IsActive = true,
                            LastName = "Jovche",
                            PhoneNumber = "0894262021",
                            TargetHours = 20
                        },
                        new
                        {
                            Id = new Guid("b37367e7-6fed-454b-95c5-646e5d755130"),
                            EmployeeNumber = "0741",
                            FirstName = "Ronan",
                            IsActive = true,
                            LastName = "O'Dwyer",
                            PhoneNumber = "0852860741",
                            TargetHours = 20
                        },
                        new
                        {
                            Id = new Guid("99c0cddf-f6e8-4bba-a86f-33952523d0bb"),
                            EmployeeNumber = "5062",
                            FirstName = "Shajahan",
                            IsActive = true,
                            LastName = "Shajahan",
                            PhoneNumber = "0894045062",
                            TargetHours = 20
                        },
                        new
                        {
                            Id = new Guid("03a5c5c9-8620-49af-b7da-e89c6a7ce123"),
                            EmployeeNumber = "2458",
                            FirstName = "Chowdhury",
                            IsActive = true,
                            LastName = "Belal",
                            PhoneNumber = "0894582680",
                            TargetHours = 20
                        });
                });

            modelBuilder.Entity("Roaster_Generator.Entities.RosterPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.Property<DateOnly>("WeekStart")
                        .HasColumnType("date")
                        .HasColumnName("week_start");

                    b.HasKey("Id");

                    b.HasIndex("WeekStart")
                        .IsUnique();

                    b.ToTable("roster_plans", (string)null);
                });

            modelBuilder.Entity("Roaster_Generator.Entities.RosterShift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<TimeOnly>("FinishTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("finish_time");

                    b.Property<Guid>("RosterPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("roster_plan_id");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("RosterPlanId", "EmployeeId", "Date", "StartTime", "FinishTime")
                        .IsUnique();

                    b.ToTable("roster_shifts", (string)null);
                });

            modelBuilder.Entity("Roaster_Generator.Entities.Shift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date")
                        .HasColumnName("date");

                    b.Property<Guid>("EmployeeId")
                        .HasColumnType("uuid")
                        .HasColumnName("employee_id");

                    b.Property<TimeOnly>("FinishTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("finish_time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId", "Date")
                        .IsUnique();

                    b.ToTable("shifts", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Roaster_Generator.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Roaster_Generator.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roaster_Generator.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Roaster_Generator.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Roaster_Generator.Entities.ApplicationUser", b =>
                {
                    b.HasOne("Roaster_Generator.Entities.Employee", "Employee")
                        .WithOne("User")
                        .HasForeignKey("Roaster_Generator.Entities.ApplicationUser", "EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Roaster_Generator.Entities.DemandColumn", b =>
                {
                    b.HasOne("Roaster_Generator.Entities.DemandPlan", "DemandPlan")
                        .WithMany("Columns")
                        .HasForeignKey("DemandPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemandPlan");
                });

            modelBuilder.Entity("Roaster_Generator.Entities.DemandRow", b =>
                {
                    b.HasOne("Roaster_Generator.Entities.DemandPlan", "DemandPlan")
                        .WithMany("Rows")
                        .HasForeignKey("DemandPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DemandPlan");
                });

            modelBuilder.Entity("Roaster_Generator.Entities.DemandValue", b =>
                {
                    b.HasOne("Roaster_Generator.Entities.DemandColumn", "Column")
                        .WithMany("Values")
                        .HasForeignKey("DemandColumnId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roaster_Generator.Entities.DemandRow", "Row")
                        .WithMany("Values")
                        .HasForeignKey("DemandRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Column");

                    b.Navigation("Row");
                });

            modelBuilder.Entity("Roaster_Generator.Entities.RosterShift", b =>
                {
                    b.HasOne("Roaster_Generator.Entities.Employee", "Employee")
                        .WithMany("RosterShifts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Roaster_Generator.Entities.RosterPlan", "RosterPlan")
                        .WithMany("Shifts")
                        .HasForeignKey("RosterPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("RosterPlan");
                });

            modelBuilder.Entity("Roaster_Generator.Entities.Shift", b =>
                {
                    b.HasOne("Roaster_Generator.Entities.Employee", "Employee")
                        .WithMany("Shifts")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Roaster_Generator.Entities.DemandColumn", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Roaster_Generator.Entities.DemandPlan", b =>
                {
                    b.Navigation("Columns");

                    b.Navigation("Rows");
                });

            modelBuilder.Entity("Roaster_Generator.Entities.DemandRow", b =>
                {
                    b.Navigation("Values");
                });

            modelBuilder.Entity("Roaster_Generator.Entities.Employee", b =>
                {
                    b.Navigation("RosterShifts");

                    b.Navigation("Shifts");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Roaster_Generator.Entities.RosterPlan", b =>
                {
                    b.Navigation("Shifts");
                });
#pragma warning restore 612, 618
        }
    }
}
