// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Roaster_Generator.Data;

#nullable disable

namespace Roaster_Generator.Data.Migrations;

[DbContext(typeof(AppDbContext))]
[Migration("20260915150000_AddFairHoursAlpha")]
partial class AddFairHoursAlpha
{
}
